### ISSUE TITLE
Exception on plugin (form) open

### ISSUE THREAD

**Issue by schwabelbauch** [incognito1234/KeePass-Custom-Icon-Dashboarder#1]
```
System.ArgumentOutOfRangeException: 
Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: 
index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CustomIconDashboarderPlugin.DashboarderForm.CreateAllEntriesList()
   at CustomIconDashboarderPlugin.DashboarderForm.ResetAllIconDashboard()
   at CustomIconDashboarderPlugin.DashboarderForm.ResetDashboard()
   at CustomIconDashboarderPlugin.DashboarderForm.InitEx()
   at CustomIconDashboarderPlugin.DashboarderForm.OnFormLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by incognito1234** [comment]
Hi schwabelbauch,

It seems that some custom icons have been corrupted. It can occur when entries are copied and pasted from database to an other one with old version of KeePass (<v2.34).

Could you please test this version of plugin - to be unzipped - and give a feedback ?
[CustomIconDashboarder.zip](https://github.com/incognito1234/KeePass-Custom-Icon-Dashboarder/files/3752943/CustomIconDashboarder.zip)

Thanks,

Jareth

**Comment by devworx-mbucher** [comment]
Thank you very much.
You are absolutly right. There were 6 broken entries.

**Comment by schwabelbauch** [comment]
Thank you very much.
You are absolutly right. There were 6 broken entries.

**Comment by tkouba** [comment]
I have the same problem and test version works (7 broken entries). When will be this functionality in stable version?
