### ISSUE TITLE
[Solved]Unhandled exception: Index out of range - must be non-negative ans

### ISSUE THREAD

**Issue by Ookmichiel** [incognito1234/KeePass-Custom-Icon-Dashboarder#11]
Hi,

When starting v1.2 of the plugin, I receive the below error; there are 2 options (Continue or Quit); when I click Continue the Plugin appears to load OK but when I click Quit, Keepass also closes.

Note that when I open the Dashboard for the 2nd time, no error appears, but the Dashboard doesn't show any icons (just empty). When I restart Keepass, I again have 1 attempt to load the Dash. Any idea?

![image](https://user-images.githubusercontent.com/43234891/121251770-861be200-c8a7-11eb-9af2-1df92ce5a62d.png)

Error details:
```
************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CustomIconDashboarderPlugin.DashboarderForm.CreateAllEntriesList()
   at CustomIconDashboarderPlugin.DashboarderForm.ResetAllIconDashboard()
   at CustomIconDashboarderPlugin.DashboarderForm.ResetDashboard()
   at CustomIconDashboarderPlugin.DashboarderForm.InitEx()
   at CustomIconDashboarderPlugin.DashboarderForm.OnFormLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.48.1.16933
    Win32 Version: 2.48.1.0
    CodeBase: file:///D:/Users/<username>/OneDrive/Apps/KeePass/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CustomIconDashboarderPlugin
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/jyUKaqqF3nhuvNXrSbJM/CustomIconDashboarderPlugin.dll
----------------------------------------
KeePassFaviconDownloader
    Assembly Version: 2.0.9.15398
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/Gfg1SEkOrgM68gIeCcCL/KeePassFaviconDownloader.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.48.1.16933
    Win32 Version: 2.48.1.16933
    CodeBase: file:///D:/Users/<username>/OneDrive/Apps/KeePass/KeePass.XmlSerializers.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by ploedman** [comment]
Same.
After downloading and selecting (10-15 entries) bigger Icons for using them with action "Pick chosen icon", the Plugin crashes with an error. 

I would assume it is to much for the Software to handle 15 request and more to save in the icon storage of KeePass. So you have to modify every entry per hand one by one and save the DB after every 5th icon.


```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.CheckedIndexCollection.get_Item(Int32 index)
   at System.Windows.Forms.ListView.CheckedListViewItemCollection.get_Item(Int32 index)
   at CustomIconDashboarderPlugin.DashboarderForm.OnModifyCustomIconClick()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

```
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.53.0.18479
    Win32 Version: 2.53.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9115.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeePersoCpp
    Assembly Version: 0.7.0.0
    Win32 Version: 0.7.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePersoCpp.DLL
----------------------------------------
IOProtocolExt
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/Plugins/IOProtocolExt.dll
----------------------------------------
KeePassDiceware
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/Plugins/KeePassDiceware.dll
----------------------------------------
CertKeyProviderPlugin
    Assembly Version: 2.0.8.3
    Win32 Version: 2.0.8.3
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/ddCaJbLUyNuUHau8NzVR/CertKeyProviderPlugin.dll
----------------------------------------
ColoredPassword
    Assembly Version: 0.15.2.0
    Win32 Version: 0.15.2
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/Z91ClPjcoqGMl7QiRwnL/ColoredPassword.dll
----------------------------------------
CustomIconDashboarderPlugin
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/ml66jkfGbNRIvecGlGT3/CustomIconDashboarderPlugin.dll
----------------------------------------
HIBPOfflineCheck
    Assembly Version: 1.7.9.0
    Win32 Version: 1.7.9.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/tH2SclB7Cev83XX5tcfx/HIBPOfflineCheck.dll
----------------------------------------
KeeAgent
    Assembly Version: 0.13.3.0
    Win32 Version: 0.13.3.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/P7Z1ljdISiXMDX9H0mC3/KeeAgent.dll
----------------------------------------
SshAgentLib
    Assembly Version: 0.9.4.0
    Win32 Version: 0.9.4.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/P7Z1ljdISiXMDX9H0mC3/SshAgentLib.DLL
----------------------------------------
SshAgentLib.WinForms
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/P7Z1ljdISiXMDX9H0mC3/SshAgentLib.WinForms.DLL
----------------------------------------
KeeAnywhere
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/s7wZhwu2wcIxHoxt9UZA/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/s7wZhwu2wcIxHoxt9UZA/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/s7wZhwu2wcIxHoxt9UZA/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/s7wZhwu2wcIxHoxt9UZA/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeeOtp2
    Assembly Version: 1.5.9.0
    Win32 Version: 1.5.9.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/jezui5GSXY0YiaQHRbdO/KeeOtp2.dll
----------------------------------------
NHotkey
    Assembly Version: 2.0.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/jezui5GSXY0YiaQHRbdO/NHotkey.DLL
----------------------------------------
Yort.Ntp
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/jezui5GSXY0YiaQHRbdO/Yort.Ntp.DLL
----------------------------------------
NHotkey.WindowsForms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/jezui5GSXY0YiaQHRbdO/NHotkey.WindowsForms.DLL
----------------------------------------
KeePassFaviconDownloader
    Assembly Version: 2.0.9.37533
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/1OitwUgK0ZI7zIh7QqK8/KeePassFaviconDownloader.dll
----------------------------------------
KeePassNewKeyExport
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/1UFKFrkOg5XGe0pIf1AO/KeePassNewKeyExport.dll
----------------------------------------
KeePassOTP
    Assembly Version: 1.6.3.0
    Win32 Version: 1.6.3
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/3kwJN2kqXysdhC8SrMS7/KeePassOTP.dll
----------------------------------------
KeePassQRCodeView
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/C5M9mOGACP5SHyoV6jQ4/KeePassQRCodeView.dll
----------------------------------------
KeePassRPC
    Assembly Version: 2.0.34.37534
    Win32 Version: 1.14.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/RBL4EiaG0zrJyrLXUs4u/KeePassRPC.dll
----------------------------------------
Fleck2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/RBL4EiaG0zrJyrLXUs4u/Fleck2.DLL
----------------------------------------
DomainPublicSuffix
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/RBL4EiaG0zrJyrLXUs4u/DomainPublicSuffix.DLL
----------------------------------------
Jayrock
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.11214.1056
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/RBL4EiaG0zrJyrLXUs4u/Jayrock.DLL
----------------------------------------
KeyManagerUI
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/PeVDcEhqkqhdKquIZBbz/KeyManagerUI.dll
----------------------------------------
KPEnhancedEntryView
    Assembly Version: 2.39.0.0
    Win32 Version: 2.4.4.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/z5YGfufREohaLySH6l5N/KPEnhancedEntryView.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.7.0.25452
    Win32 Version: 2.7.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/z5YGfufREohaLySH6l5N/ObjectListView.DLL
----------------------------------------
MultiCertKeyProvider
    Assembly Version: 2.0.8.3
    Win32 Version: 2.0.8.3
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/cGY4ospf1XOzBr5RWxH8/MultiCertKeyProvider.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OtpKeyProv
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/vw6dJNdcIUobclhgsJ8a/OtpKeyProv.dll
----------------------------------------
PasswordChangeAssistant
    Assembly Version: 2.15.1.0
    Win32 Version: 2.15.1
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/6rL5ieyH1DZ1k8r8H7rf/PasswordChangeAssistant.dll
----------------------------------------
SourceForgeUpdateChecker
    Assembly Version: 2.22.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/NMgQXA1bv5uJs7SpUDm3/SourceForgeUpdateChecker.dll
----------------------------------------
TwoFactorQRCodeReader
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/VfGLTMnb7gVTd4qDJVK4/TwoFactorQRCodeReader.dll
----------------------------------------
WebAutoType
    Assembly Version: 2.42.0.0
    Win32 Version: 6.8.2.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/0nZNjgcWcZ3goIqtRbPG/WebAutoType.dll
----------------------------------------
YetAnotherFaviconDownloader
    Assembly Version: 1.2.5.0
    Win32 Version: 1.2.5.0
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/2LJmsbSV0R5vuZbY08hl/YetAnotherFaviconDownloader.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.53.0.18479
    Win32 Version: 2.53.0.18479
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Jayrock.Json
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.13422.2206
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/RBL4EiaG0zrJyrLXUs4u/Jayrock.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///C:/Users/foo-bar/AppData/Local/KeePass/PluginCache/P7Z1ljdISiXMDX9H0mC3/BouncyCastle.Crypto.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box. 
```

**Comment by incognito1234** [comment]
Hi,
The last release should solve this issue.
Please try it and give a feedback.
Thanks
